obstacle_range: 2.5
raytrace_range: 3.0
robot_radius: 0.2
inflation_radius: 0.05

observation_sources: laser_scan_sensor point_cloud_sensor

laser_scan_sensor: {sensor_frame: /pioneer3dx/front_laser, data_type: LaserScan, topic: /pioneer3dx/front_laser/scan, marking: true, clearing: true}

point_cloud_sensor: {sensor_frame: /pioneer3dx/front_camera, data_type: PointCloud, topic: /camera/depth/points, marking: true, clearing: true}